#pragma once

#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <cmath>
#include <iostream>
#include <string>
#include <functional>
#include <memory>
#include <vector>
#include <stdint.h>
#include "util/Benchmark.h"
#include "util/Utils.h"
#include "util/Array.h"
#include "util/MArray.h"
#include "unit/Vectors.h"
#include "unit/Color.h"
#include "glComponent/GLSLInterface.h"
